#cSpell:disable
[mypy]
# Use the Django plugin
plugins = mypy_django_plugin.main

# Enable strict type checking for better coverage
strict = True

# Exclude migrations from type checking
exclude = migrations

# Optional: ignore missing imports for third-party packages
ignore_missing_imports = True

[mypy-django_unfold.*]
ignore_missing_imports = True

[mypy-manage]
ignore_errors = True

[mypy.plugins.django-stubs]
# Path to Django settings module
django_settings_module = "jules_shop.settings"
