# Generated by Django 5.2.6 on 2025-12-16 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cartitem_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='price_snapshot',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
