# Generated by Django 5.2.6 on 2025-09-26 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_address_line1',
            field=models.CharField(default='test-address', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address_line2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_country',
            field=models.CharField(default='GHANA', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_digital_address',
            field=models.CharField(default='GH-02-test', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_name',
            field=models.CharField(default='test-user', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_region',
            field=models.CharField(default='Ashanti', max_length=100),
        ),
    ]
