# Generated by Django 5.2.6 on 2025-09-26 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_shipping_address_line1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_address_line1',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_digital_address',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_region',
            field=models.CharField(max_length=100),
        ),
    ]
